Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/objects/Data_Category_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>DataCategoryGroup__c</fullName>
        <label>DataCategoryGroup</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Category__c</fullName>
        <label>New Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TF_EX_Data Category Mapping</label>
    <nameField>
        <displayFormat>DCM-{00000}</displayFormat>
        <label>Data Category Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Category Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/objects/Knowledge__kav.object
<CustomObject>
    <fields>
        <fullName>KnowledgeContent__c</fullName>
        <label>Knowledge Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MindtouchExternalId__c</fullName>
        <label>Mindtouch External Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/objects/KnowledgeCategoryMap__c.object
<CustomObject>
    <fields>
        <fullName>New_Category__c</fullName>
        <label>New Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TF_EX_Knowledge Category Map</label>
    <nameField>
        <label>Knowledge Category Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Category Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/classes/TF_EX_KnowledgeCategAssignmentBatchTest.cls
@isTest
private class TF_EX_KnowledgeCategAssignmentBatchTest {
    
    @TestSetup
    static void setupData() {
        // Create KnowledgeCategoryMap__c records (unprocessed)
        List<Knowledge__kav> records = new List<Knowledge__kav>();
        List<Data_Category_Mapping__c> categMapList = new List<Data_Category_Mapping__c>();

        // Record with HTML content containing helpme.tebra.com link
        Knowledge__kav rec1 = new Knowledge__kav(
            urlName                 = 'test-Article-1',
            Title                   = 'Test Article 1',
            KnowledgeContent__c    = 'Content of Article 1',
            MindtouchExternalId__c  = '001'
        );
        records.add(rec1);

        // Record with blank HTML content
        Knowledge__kav rec2 = new Knowledge__kav(
            urlName                 = 'test-Article-2',
            Title                   = 'Test Article 2',
            KnowledgeContent__c    = 'Content of Article 2',
            MindtouchExternalId__c  = '002'
        );
        records.add(rec2);
        
        Data_Category_Mapping__c categMap = new Data_Category_Mapping__c(
            External_Id__c = '001',
            DataCategoryGroup__c = 'External',
            New_Category__c = 'All'
        );
        categMapList.add(categMap);
        
        Data_Category_Mapping__c categMap1 = new Data_Category_Mapping__c(
            External_Id__c = '002',
            DataCategoryGroup__c = 'External',
            New_Category__c = 'All'
        );
        categMapList.add(categMap1);
        
        insert records;
        insert categMapList;
    }
    @isTest
    static void testDataCategAssignment() {
        TF_EX_KnowledgeCategoryAssignmentBatch batch =
            new TF_EX_KnowledgeCategoryAssignmentBatch();

        Test.startTest();
        Database.executeBatch(batch, 200);
        Test.stopTest();
    }
    @isTest
    static void testDataCategAssignmentWithTitle() {
        TF_EX_KnowledgeCategoryAssignmentBatch batch =
            new TF_EX_KnowledgeCategoryAssignmentBatch('Article');

        Test.startTest();
        Database.executeBatch(batch, 200);
        Test.stopTest();
    }
}