Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/objects/Data_Category_Mapping__c.object
<CustomObject>
    <label>TF_EX_Data Category Mapping</label>
    <nameField>
        <displayFormat>DCM-{00000}</displayFormat>
        <label>Data Category Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Category Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/objects/Knowledge__kav.object
<CustomObject>
    <fields>
        <fullName>KnowledgeContent__c</fullName>
        <label>Knowledge Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MindtouchExternalId__c</fullName>
        <label>Mindtouch External Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/objects/MindTouch_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>SiteURL__c</fullName>
        <label>NewURL</label>
        <type>Url</type>
    </fields>
    <label>TF_EX_MindTouch_Config</label>
    <pluralLabel>MindTouch_Configs</pluralLabel>
</CustomObject>

Components/Mindtouch Knowledge Migration/Mindtouch Knowledge Migration/classes/TF_EX_MindTouchUpdateIntArtLinksTest.cls
@isTest
private class TF_EX_MindTouchUpdateIntArtLinksTest {
    
    @TestSetup
    static void setupData() {
        MindTouch_Config__mdt metadataRecord = [SELECT id, SiteURL__c FROM MindTouch_Config__mdt WHERE SiteURL__c !=null Limit 1];
        // Create Knowledge__kav records (unprocessed)
        List<Knowledge__kav> records = new List<Knowledge__kav>();
        List<Data_Category_Mapping__c> categMapList = new List<Data_Category_Mapping__c>();

        // Record with HTML content containing helpme.tebra.com link
        Knowledge__kav rec1 = new Knowledge__kav(
            urlName                 = 'test-Article-1',
            Title                   = 'Test Article 1',
            KnowledgeContent__c    = '<a href="' + metadataRecord.siteURL__c + '/test-article-2">Test Link</a>',
            MindtouchExternalId__c  = '001'
        );
        records.add(rec1);

        // Record with blank HTML content
        Knowledge__kav rec2 = new Knowledge__kav(
            urlName                 = 'test-Article-2',
            Title                   = 'Test Article 2',
            KnowledgeContent__c    = 'Content of Article 2',
            MindtouchExternalId__c  = '002'
        );
        records.add(rec2);

        insert records;
    }

    @isTest
    static void rewriteInternalLinkTest() {
        TF_EX_MindTouchUpdateInternalArtLinks batch =
            new TF_EX_MindTouchUpdateInternalArtLinks();

        Test.startTest();
        Database.executeBatch(batch, 200);
        Test.stopTest();
    }
}